language: php
php:
  - "5.5"
  - "5.4"
  - "hhvm"

install:
  - sudo apt-get update
  - travis_retry composer self-update && composer --version
  - travis_retry composer global require --no-progress "fxp/composer-asset-plugin:1.1.1"
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install --prefer-dist --no-interaction --no-progress
