language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

before_install:
  - sudo apt-get update

install:
  - travis_retry composer self-update && composer --version
  - travis_retry COMPOSER_ROOT_VERSION=dev-master composer install --prefer-dist --no-interaction --dev

after_script:
  - travis_retry wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
